clear all;
Date = '2017_0525';
% Read = fullfile('D:\Seneory_Feedback\S1_M1_ICMS_5\S1_recording\Pressing_Lever_preprocessing',Date);
Read_1 = fullfile('D:\Seneory_Feedback\S1_M1_ICMS_2\Camera_Track',Date);
mkdir(fullfile('D:\Seneory_Feedback\S1_M1_ICMS_2\Acceleration',Date));
Write = fullfile('D:\Seneory_Feedback\S1_M1_ICMS_2\Acceleration',Date);
% file = dir([Read '\*50Hz*ms.mat']);
file_1 = dir([Read_1 '\*.mat']);
% load([Read '\' file(1).name]);
load([Read_1 '\' file_1(1).name]);
[acceleration,acceleration_X,acceleration_Y,velocity,velocity_X,velocity_Y] = Get_Camera_acceleration(Camera_Position);
Acceleration_velocity.Trajectory = Camera_Position;
Acceleration_velocity.Acceleration.acceleration = acceleration;
Acceleration_velocity.Acceleration.acceleration_X = acceleration_X;
Acceleration_velocity.Acceleration.acceleration_Y = acceleration_Y;
Acceleration_velocity.Velocity = velocity;
Acceleration_velocity.Velocity_X = velocity_X;
Acceleration_velocity.Velocity_Y = velocity_Y;
save(fullfile(Write,'Acceleration_velocity'),'Acceleration_velocity');